matches:
  - trigger: ":uuid7"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - "python"
            - "wrapper.py"
            - "7"

  - trigger: ":uuid4"
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - "python"
            - "wrapper.py"
            - "4"